throwError: tạo err bằng một message mới (return observable)

catchError: tạo err bằng cách biến đổi error đó thành một value thông thường

retry: chỉ nên xử dụng với get

defaultIfEmpty: nếu observable return empty thì trả về giá trị mặc định